isDevelopment: true
port: 3030
log:
  windowsPath:  D:\\Personal-Blog-Log\\log
  macPath: ~\\worker\\Personal-Blog-Log\\log
  maxCount: 30
database:
  mysql:
    charset: utf8
    host: 127.0.0.1
    user: root
    password: 123456
    name: personal-blog-db
    pool:
      max: 20
      min: 5